Add without_null_override mergo data modifier optional flag
isometry/terraform-provider-deepmerge pull request #45
Opened 2024-10-16 00:18 UTC by shaneramey

Accommodates the use-case raised in #39 by leveraging mergo's ["Transformers"](https://github.com/darccio/mergo?tab=readme-ov-file#transformers).

The merge logic, when the `"without_null_override"` parameter is set, will not merge null values over non-null values.

Example usage:

```
resource "terraform_data" "merged" {
  input = provider::deepmerge::mergo("without_null_override", m1, m2, m3)
}
```

2024-10-16 10:36 UTC, isometry requested changes
Thanks for the contribution!

I have one small request to rename the variable (and associated references), but otherwise looks good!

2024-10-16 10:36 UTC, isometry commented on internal/provider/mergo_function.go
> +			case `"without_null_override"`:
Would you please rename the variable to `"no_null_override"`?

2024-10-16 10:39 UTC, isometry commented on internal/provider/mergo_function.go
> +type noNullOverrideTransformer struct {
What do you think about moving this under `pkg/transformers/` to facilitate its use in other `mergo` projects?

2024-10-19 07:13 UTC, shaneramey commented on internal/provider/mergo_function.go
> +			case `"without_null_override"`:
done, thanks!

2024-10-19 16:41 UTC, merged

2024-10-19 16:45 UTC, isometry commented
Thanks, @shaneramey !